In [39]:
import json
import pandas as pd

with open(r"C:\Users\samue\git\figma-visual-understanding\eval\results\icon_matching\matching-eval-mined-threshold.jsonl", encoding="utf-8") as file:
    evaluation = json.load(file)

crops_df = pd.DataFrame(evaluation["crops"])

In [40]:
print(f"Threshold: {evaluation['detection_threshold']}")
print(f"Thresholding on **{evaluation['detection_score_name']}** score")
print(f"Precision: {evaluation['precision']}")
print(f"Recall: {evaluation['detection_score_name']}")
print(f"MRR: {evaluation['mean_reciprocal_rank']}")
print(f"E2E Accuracy: {evaluation['end_to_end_accuracy']}")
print(f"Detection Accuracy: {evaluation['detection_accuracy']}")  # Maybe non ha tanto senso

Threshold: 0.973675221184481
Thresholding on **final** score
Precision: 1.0
Recall: final
MRR: 0.983051
E2E Accuracy: 0.990476
Detection Accuracy: 0.990476

In [41]:
crops_df

,crop_path,expected_label,predicted_label,final_score,primary_score,secondary_score,threshold_score,detected,true_label_rank,reciprocal_rank,outcome
0,C:\Users\samue\git\figma-visual-understanding\...,,NaN,0.917205,0.985394,0.644447,0.917205,False,NaN,0.0,true_negative
1,C:\Users\samue\git\figma-visual-understanding\...,,NaN,0.939161,0.982910,0.764164,0.939161,False,NaN,0.0,true_negative
2,C:\Users\samue\git\figma-visual-understanding\...,,NaN,0.906471,0.971429,0.646639,0.906471,False,NaN,0.0,true_negative
3,C:\Users\samue\git\figma-visual-understanding\...,pen,pen,0.991593,0.998106,0.965544,0.991593,True,1.0,1.0,true_positive
4,C:\Users\samue\git\figma-visual-understanding\...,comment,comment,0.994945,0.997789,0.983567,0.994945,True,1.0,1.0,true_positive
...,...,...,...,...,...,...,...,...,...,...,...
100,C:\Users\samue\git\figma-visual-understanding\...,,NaN,0.939060,0.989385,0.737759,0.939060,False,NaN,0.0,true_negative
101,C:\Users\samue\git\figma-visual-understanding\...,,NaN,0.925172,0.984218,0.688986,0.925172,False,NaN,0.0,true_negative
102,C:\Users\samue\git\figma-visual-understanding\...,remove,remove,1.000000,1.000000,1.000000,1.000000,True,1.0,1.0,true_positive
103,C:\Users\samue\git\figma-visual-understanding\...,,NaN,0.919818,0.979445,0.681312,0.919818,False,NaN,0.0,true_negative
104,C:\Users\samue\git\figma-visual-understanding\...,,NaN,0.919738,0.979445,0.680909,0.919738,False,NaN,0.0,true_negative

In [42]:
print(f"Min score (detectable icons): {crops_df[crops_df.expected_label!=''].threshold_score.min().item()}")
print(f"Max score (non-detectable icons): {crops_df[crops_df.expected_label==''].threshold_score.max().item()}")

Min score (detectable icons): 0.9736482878364583
Max score (non-detectable icons): 0.9736752211844809

In [43]:
crops_df[(crops_df.expected_label!='') & (crops_df.expected_label != crops_df.predicted_label)]

,crop_path,expected_label,predicted_label,final_score,primary_score,secondary_score,threshold_score,detected,true_label_rank,reciprocal_rank,outcome
51,C:\Users\samue\git\figma-visual-understanding\...,flip vertical,NaN,0.973648,0.995347,0.886855,0.973648,False,1.0,0.0,false_negative_rejected

In [44]:
crops_df[(crops_df.expected_label!='') & (crops_df.expected_label != crops_df.predicted_label)].iloc[0].crop_path

'C:\\Users\\samue\\git\\figma-visual-understanding\\outputs\\icon-candidates\\evaluation_candidates\\0004_full_panel_candidate-027.png'